### ISSUE TITLE
TIPC问题

### ISSUE THREAD

**Issue by kongdebug** [justld/ENCNet_paddle#1]
您好，我在做其他论文复现时，只得到.pdparams文件，该怎么样才能转为TIPC链接呢？您是否可以推荐例子或者教程呢？

**Comment by justld** [comment]
你好，我的TIPC还没验收通过，可以参考下面：

https://github.com/PaddlePaddle/models/tree/tipc/community/repo_template/test_tipc  https://github.com/PaddlePaddle/PaddleOCR/tree/dygraph/test_tipc

**Comment by kongdebug** [comment]
好的，谢谢您！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月25日(周四) 晚上7:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [justld/ENCNet_paddle] TIPC问题 (Issue #1)




 
你好，我的TIPC还没验收通过，可以参考下面：
 
https://github.com/PaddlePaddle/models/tree/tipc/community/repo_template/test_tipc  https://github.com/PaddlePaddle/PaddleOCR/tree/dygraph/test_tipc
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
